name: himatubu_chat
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  enum_to_string: ^1.0.14
  equatable: ^2.0.3
  meta: ^1.2.4
  cloud_firestore: ^4.0.4
  firebase_auth: 4.1.0
  flutter_datetime_picker: ^1.4.0
  firebase_core: 2.1.1
  firebase_storage: 11.0.3
  image_picker: ^0.8.5
  flutter_riverpod: ^1.0.0
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  uuid: ^3.0.0
  logger: ^1.0.0
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  state_notifier: ^0.7.0
  form_field_validator: ^1.1.0
  freezed_annotation: ^1.1.0
  age_calculator: ^1.0.0
  dartz: ^0.10.1
  dio: ^4.0.4
  flutter_platform_widgets: ^2.0.0
  lottie: ^1.2.1
  connectivity_plus: ^2.2.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  freezed: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/core/
    - assets/images/auth/login_bg.png
    - assets/json/loading_animation.json
